fc-hackathon-imaging-B:
  # For each dataset we use data (X_name) and labels (y_name)
  local_dataset:
    train: "_train.npy"
    val_l: "_val_l.npy"

  global_dataset:
    test: "_test.npy"
    val_gl: "_val_gl.npy"

  model:
    image_size: 28
    name: "resnet50"
    is_pretrained: False
    batch_size: 128
    optimizer: 'adam' 
    lr: 0.01
    momentum: 0.9

  federated_params:
    num_rounds: 20
    weighted_aggregation: False
    local_epochs: 25

  test_on_val: False



