fc-hackathon-imaging-B:
  # For each dataset we use data (X_name) and labels (y_name)
  local_dataset:
    train: "_train.npy"
    val_l: "_val_l.npy"

  global_dataset:
    test: "_test.npy"
    val_gl: "_val_gl.npy"

  model:
    name: "resnet34"
    batch_size: 32
    optimizer: 'sgd' 
    lr: 0.01
    momentum: 0.9

  federated_param:
    num_rounds: 10
    weighted_aggregation: False



